base_images:
  ocp_4.17_base-rhel9:
    name: "4.18"
    namespace: ocp
    tag: base-rhel9
  ocp_builder_rhel-9-golang-1.22-openshift-4.17:
    name: builder
    namespace: ocp
    tag: rhel-9-golang-1.22-openshift-4.17
binary_build_commands: make build --warn-undefined-variables
build_root:
  from_repository: true
images:
- dockerfile_path: Dockerfile
  inputs:
    ocp_4.17_base-rhel9:
      as:
      - registry.ci.openshift.org/ocp/4.17:base-rhel9
    ocp_builder_rhel-9-golang-1.22-openshift-4.17:
      as:
      - registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.22-openshift-4.17
  to: kube-proxy
promotion:
  to:
  - name: "4.18"
    namespace: ocp
releases:
  initial:
    integration:
      name: "4.18"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.18"
      namespace: ocp
resources:
  '*':
    requests:
      cpu: "3"
      memory: 6Gi
test_binary_build_commands: make build GO_BUILD_FLAGS:='-race' --warn-undefined-variables
tests:
- as: security
  optional: true
  steps:
    env:
      ALL_PROJECTS: "true"
      PROJECT_NAME: standalone-kube-proxy
    workflow: openshift-ci-security
zz_generated_metadata:
  branch: main
  org: openshift
  repo: standalone-kube-proxy
